<?php

//Load functions
//module_load_include('inc', 'band_booking_registration_relaunch', 'includes/band_booking_registration_relaunch_batch.inc');

/**
 * Implements hook_menu().
 *
 * @ingroup signup_core
 */
function band_booking_registration_relaunch_menu() {
  $path = drupal_get_path('module', 'band_booking_registration_relaunch') . '/includes';

  // Different relaunch menu entries.
  return array(
    // All nodes automatically with cron.
    'relaunch_batch_cron' => array(
      'title' => 'Batch relaunch all',
      'description' => 'Batch to auto relaunch all registrations',
      'page callback' => '_band_booking_registration_relaunch_setup_batch',
      'page arguments' => array('NULL', FALSE, TRUE),
      'access arguments' => array('relaunch waiting users registration'),
      'file' => 'band_booking_registration_relaunch_batch.inc',
      'file path' => $path,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_permission().
 */
function band_booking_registration_relaunch_permission() {
  return array(
    'relaunch waiting users registration' => array(
      'title' => t('Relaunch band booking registrations'),
    ),
  );
}

/**
 * Launch batch operations in hook_cron.
 */
function band_booking_registration_relaunch_cron() {
  module_load_include('inc', 'band_booking_registration_relaunch', 'includes/band_booking_registration_relaunch_batch.inc');
  _band_booking_registration_relaunch_setup_batch('NULL', FALSE);
}

/**
 * @TODO.
 *
 * Define access right
 *
 * @param $node
 * @param $permission
 *
 * @return bool
 */
function _band_booking_registration_relaunch_node_relaunch_waiting_users_registration_access($node, $permission) {
  if (user_access($permission) && !empty($node->field_inscriptions['und'][0]['registration_type'])) {
    return TRUE;
  }
  return FALSE;
}