<?php

// @TODO : test if necessary.
/*
function belive_registration_init() {
  //dpm('init romain');
  $states = _get_band_booking_registration_states();
  //_create_belive_registration_workflow( $states );
}
*/
function _create_band_booking_registration_workflow( $states ) {
  // Create a workflow.
  $workflow = workflow_create('workflow_band_booking_booking');
  //$workflow->save();

  // Create States for the workflow.
  foreach ($states as $key => $state) {
    //TODO IF default => name = creation
    $workflow_state = $workflow->createState($state['name']);
    $workflow_state->save();
  }

  // Create Transitions for the workflow.
  /*  $roles = array(-1, 5);
  $t1 = $workflow->createTransition($s1->sid, $s2->sid);
  $t1->label = 'transitions t1';
  $t1->roles = $roles;
  // The transition was initially saved in createState,
  // but without roles and name.
  $t1->save();

  $roles = array(-1, 6);
  $t2 = $workflow->createTransition($s2->sid, $s3->sid);
  $t2->label = 'transitions t2';
  $t2->roles = $roles;
  $t2->save();*/

  // Remove the workflow and its components.
  //$workflow->delete();
}
