<?php
/**
 * @file
 * Code for the Belive admin feature.
 */

include_once 'belive_admin.features.inc';

/**
 * @param $items
 */
function belive_admin_menu_alter(&$items) {
  // Tableau des menu items strictement réservés à l'admin.
  $menu_items_strictly_admin = [
    'admin/content',
    'node/add'
  ];

  // Pour chaque, si existe, ajouter l'access callb.
  foreach ($menu_items_strictly_admin as $menu_item_strictly_admin) {
    if (isset($items[$menu_item_strictly_admin])) {
      // Restric visibility of admin menu item.
      //$items[$menu_item_strictly_admin]['access callback'] = 'belive_admin_menu_item_admin_restricted_access';
    }
  }
}

function belive_admin_menu_item_admin_restricted_access(){
  global $user;
  dpm($user);

  //If user has the right to edit registration
  /*if (!user_access($permission)) {
    dpm('user can not access form');
    return FALSE;
  }*/
  // Droit d'accéder ET Strictement admin.
  return TRUE;

  // Security.
  //return FALSE;
}