<?php
/**
 * @file
 * Code for the Band booking base feature.
 */

/**
 * Implements hook_menu().
 *
 * @ingroup signup_core
 */
function band_booking_dev_menu() {
  return array(
    // Admin page with reminder links.
    'page-de-test' => array(
      'title' => 'Page de test',
      'page callback' => '_band_booking_dev_test_page_view',
      'page arguments' => array(),
      'access arguments' => array(TRUE),
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

function _band_booking_dev_test_page_view() {
  $text = t('Reminder sent to @name for performance "@perf"', array(
    '@name' => 'Name',
    '@perf' => 'Test google',
  ));

  /*
  try {
    //mail('romain.trenet@gmail.com', 'Hello world', 'Testing Postfix');
    dpm('ok');
  }
  catch (Exception $e) {
    dpm('no ok');
  }
  */
  $nid = 424;

  // By default, send to every statuses.
  $accepted_registration_statuses = array();
  // @todo Get option "bb_mail_list_allow_refused_registration".
  $allow_refused_registration = variable_get('bb_mail_list_allow_refused_registration', FALSE);
  if (!$allow_refused_registration) {
    $accepted_registration_statuses = array(WAITING_SYSTEM_NAME, ACCEPTED_SYSTEM_NAME);
  }
  $mail_list = _get_node_registered_users_mail_list($nid, $accepted_registration_statuses);
  $users_mail_list = implode ( ',', $mail_list);
  dpm($mail_list);
  dpm($users_mail_list);

  return $text;
}
