<?php
/**
 * @file
 * Code for the Band booking admin feature.
 */

include_once 'band_booking_admin.features.inc';

function band_booking_admin_admin_paths() {
  $paths = array(
    'admin/band_booking_dashboard' => TRUE,
  );
  return $paths;
}

function band_booking_admin_menu() {
  return [
    // Admin dashboard path and local action.
    'admin/band_booking_dashboard' => array(
      'title' => 'Dashboard',
      'description' => 'Dashboard for Band Booking',
      'weight' => -50,
      'menu_name' => 'management',
      'page callback' => '_band_booking_admin_dashboard_page_view',
      'access arguments' => array('administer band booking'),
      'file' => 'includes/band_booking_admin_dashboard_page_view.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/band_booking_dashboard/add_performance' => array(
      'title' => 'Add performance',
      'page callback' => 'drupal_goto',
      'page arguments' => array('node/add/performance'),
      'access arguments' => array('create performance content'),
      'type' => MENU_LOCAL_ACTION,
    ),

    // Local action on admin performances view.
    'admin/performances/add_performance' => array(
      'title' => 'Add performance',
      'page callback' => 'drupal_goto',
      'page arguments' => array('node/add/performance'),
      'access arguments' => array('create performance content'),
      'type' => MENU_LOCAL_ACTION,
    ),

    // Local action on admin artists view.
    'admin/artists/list/add_artist' => array(
      'title' => 'Add artist',
      'page callback' => 'drupal_goto',
      'page arguments' => array('artist/register'),
      'access arguments' => array('create users'),
      'type' => MENU_LOCAL_ACTION,
    ),
  ];
}

/**
 * Alter menu items, specially for Admin parts.
 *
 * @param $items
 *   List of menu items.
 */
function band_booking_admin_menu_alter(&$items) {
  // Rearrange menu items and permissions, between strictly admin reserved items, and manager items.
  $menu_items_strictly_admin = [
    // Ensure Manager only access to 'prestation' node add form.
    'node/add' => [
      'roles' => [BB_ADMINISTRATOR_RID, BB_MANAGER_RID],
      'permissions' => ['administer nodes']
    ],
    // Force "admin people" paths to be inaccessible even if Manager role has the right.
    'admin/people' => [
      'roles' => [BB_ADMINISTRATOR_RID,],
      'permissions' => ['create users', 'administer users']
    ],
    'admin/people/create' => [
      'roles' => [BB_ADMINISTRATOR_RID,],
      'permissions' => ['create users', 'administer users']
    ],
    'admin/config/people/accounts' => [
      'roles' => [BB_ADMINISTRATOR_RID,],
      'permissions' => ['create users', 'administer users']
    ],
    // Ensure Manager and Admin can access it, even if they are logged.
    'artist/register' => [
      'roles' => [BB_ADMINISTRATOR_RID, BB_MANAGER_RID],
      'permissions' => ['create users']
    ],
  ];

  // For each path, add associated arguments and special access function.
  foreach ($menu_items_strictly_admin as $path => $options) {
    if (isset($items[$path])) {
      $args = array(
        'roles' => !empty($options['roles']) ? $options['roles'] : [],
        'permissions' => !empty($options['permissions']) ? $options['permissions'] : [],
        'path' => [$path]
      );
      $items[$path]['access arguments'] = $args;
      $items[$path]['access callback'] = 'band_booking_admin_restricted_access';
    }
  }

  // Change entity register access.
  /*if (isset($items['node/%entity_object/register'])) {
    //Remove the tab for all node type
    $items['node/%entity_object/register']['type'] = MENU_CALLBACK;

    // Avoid register self form for performance node type.
    $items['node/%entity_object/register']['access callback'] = 'band_booking_admin_register_page_access';
  }

  // Change registrations page on node.
  if (isset($items['node/%entity_object/registrations'])) {
    $items['node/%entity_object/registrations']['page callback'] = 'band_booking_admin_node_registrations_view';
  }*/

  // @todo.
  foreach (registration_get_registration_instances() as $instance) {
    $type = $instance['entity_type'];
    if (!in_array($type, array('registration', 'registration_type'))) {

      // Temporary.
      $items[$type . '/%entity_object/registrations']['access callback'] = FALSE;

      $items[$type . '/%entity_object/registrations/list']['access callback'] = FALSE;
      $items[$type . '/%entity_object/registrations/settings']['access callback'] = FALSE;
      $items[$type . '/%entity_object/registrations/broadcast']['access callback'] = FALSE;

      // Remove the tab for all type.
      $items[$type . '/%entity_object/register']['type'] = MENU_CALLBACK;
      // Avoid register self form.
      $items[$type . '/%entity_object/register']['access callback'] = 'band_booking_admin_register_page_access';

      // Change registrations page.
      $items[$type . '/%entity_object/registrations']['page callback'] = 'band_booking_admin_node_registrations_view';
    }
  }
}

/**
 * Restricted access for Band booking admin parts, per role and permissions.
 *
 * @param null $rid
 *   The administrator role ID.
 * @param null $permissions
 *   The permissions array to pass.
 *
 * @return bool
 *   If user has access or no.
 */
function band_booking_admin_restricted_access($rids = NULL, $permissions = NULL, $path = NULL){
  global $user;

  /*dpm($rids);
  dpm($permissions);*/

  $has_one_role = FALSE;
  $has_permission = FALSE;

  //if (isset($rid['rid'])) {
  if (!empty($rids)) {
    //dpm($rids);
    // User has no administrator role.
    foreach ($rids as $rid) {
      if (user_has_role($rid, $user)) {
        $has_one_role = TRUE;
      }
    }

    if (!$has_one_role) {
      /*if ($path[0] == 'admin/people/create') {
        dpm('no role...');
      }*/
      return FALSE;
    }

    /*if ($path[0] == 'admin/people/create') {
      dpm('role passed');
    }*/
  }

  // Has administrator role. Test every permissions.
  if (!empty($permissions)) {
    $has_permission = TRUE;
    foreach ($permissions as $permission) {
      if (!user_access($permission, $user)) {
        /*if ($path[0] == 'admin/people/create') {
          dpm('pas le droit d acceder');
        }*/
        $has_permission = FALSE;
        return FALSE;
      }
    }
    /*if ($path[0] == 'admin/people/create') {
      dpm('permissions ok');
    }*/
  }

  // If all passed.
  if ($has_one_role && $has_permission) {
    /*if ($path[0] == 'admin/people/create') {
      dpm('all passed');
    }*/
    return TRUE;
  }

  /*if ($path[0] == 'admin/people/create') {
    dpm('rien');
  }*/

  // Security.
  return FALSE;
}

// @TODO put in inc file
function band_booking_admin_node_registrations_view () {
  return views_embed_view('registrations', 'block_nid_registration');
}

// @todo.
function band_booking_admin_register_page_access($type, $node){
  if ( $node->type == 'performance' ) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_permission().
 *
 * @ingroup registration_core
 */
function band_booking_admin_permission() {
  $permissions = array(
    'administer band booking' =>  array(
      'title' => t('Administer Band Booking'),
    ),
  );

  return $permissions;
}