<?php

/**
 * Implements hook_theme().
 */
function belive_user_theme($existing, $type, $theme, $path) {
  return array(
    'user_quick_access_block' => array(
      'variables' => array(),
      'template' => 'template/user_quick_access_block'
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function belive_user_block_info() {
  $blocks['user_quick_access'] = array(
    'info' => t('User quick access'),
    'cache' => DRUPAL_CACHE_PER_USER,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function belive_user_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'user_quick_access':
      global $user;
      $block['subject'] = $user->name;//t('My informations');
      $block['content'] = belive_user_user_quick_access_block_content();
      $block['block_html_id'] = drupal_html_id('block-belive-user-user-quick-access');
      break;
  }
  return $block;
}

/**
 * Get export links
 *
 * @code $link = array('text' => 'link text', 'path' => 'drupal path', 'options' => array());
 */
function belive_user_user_quick_access_block_content() {
  //Links info to poulate $links array, passed to the template

  global $user;
  global $base_url;
  $links = array();
  $links['my_account'] = array(
    'text' => t('My account'),
    'path' => $base_url . '/user',
  );
  $links['my_performances'] = array(
    'text' => t('My performances'),
    'path' => $base_url . '/mes-prestations',
  );
  /*$links['all_performances'] = array(
    'text' => t('All performances'),
    'path' => $base_url . '/les-prestations',
  );*/
  $links['edit_account'] = array(
    'text' => t('Edit my account'),
    'path' => $base_url . '/user/' . $user->uid . '/edit',
  );
  $links['logout'] = array(
    'text' => t('Logout'),
    'path' => $base_url . '/user/logout',
  );


  return theme('user_quick_access_block', array('links' => $links));
}

/*function belive_user_form_alter(&$form, &$form_state, $form_id)
{
	watchdog('form id', $form_id);
	//$form['actions'][] = array('#markup' => l(t('Request new password'),'/user/password'));
}*/

function belive_user_form_user_pass_alter(&$form, &$form_state, $form_id)
{
	$form['actions'][] = array('#markup' => l(t('Log in'),'/user'));
}

/**
 * Implements hook_block_form_FORM_ID_alter().
 * Add a "request password" link
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function belive_user_form_user_login_alter(&$form, &$form_state, $form_id)
{
	$form['actions'][] = array('#markup' => l(t('Request new password'),'/user/password'));
}

/**
 * Implementation of hook_menu_alter().
 * Remember to clear the menu cache after adding/editing this function.
 */
function belive_user_menu_alter(&$items) {
	// Removing certain local navigation tabs that are either undesired or need to be custom relocated.
	
	// Set these tabs to MENU_CALLBACK, so they still register the path, but just don't show the tab:
	/*$items['node/%node/track']['type'] = MENU_CALLBACK;
	$items['user/%user/track']['type'] = MENU_CALLBACK;
	$items['search/user/%menu_tail']['type'] = MENU_CALLBACK;*/
	
	// Fully unset these tabs and their paths, don't want them at all. This breaks the path as well:
	//unset($items['user/%user/example']);
	$test = 'test';
	//$items['user/%user/track']['type'] = MENU_CALLBACK;
}