<?php
/**
 * @file
 * Code for the Band booking performance feature.
 */

include_once 'band_booking_performance.features.inc';

/**
 * Implements hook_field_formatter_info().
 */
function band_booking_performance_field_formatter_info() {
  return array(
    // the key must be unique, so it's best to prefix with your module's name.
    'band_booking_performance_confirmation_icon' => array(
      // the label is is what is displayed in the select box in the UI.
      'label' => t('Confirmation icon'),
      // field types is the important bit!! List the field types your formatter is for.
      'field types' => array('list_text'),
      // You can usually leave 'multiple values' as follows:
      //'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view(). This code just passes straight
 * through to a theme function, band_booking_performance_formatter_FORMATTER
 * (e.g. band_booking_performance_formatter_band_booking_performance_absolute_url).
 */
function band_booking_performance_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  foreach ($items as $delta => $item) {
    $elements[$delta] = array(
      '#markup' => theme('band_booking_performance_formatter_'. $display['type'], array('element' => $item, 'field' => $instance)),
    );
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function band_booking_performance_theme() {
  return array(
    // The theme function that our formatter uses:
    'band_booking_performance_formatter_band_booking_performance_confirmation_icon' => array(
      'variables' => array('element' => NULL),
    ),
  );
}

/**
 * Theme function for 'band_booking_performance_confirmation_icon' icon field formatter.
 */
function theme_band_booking_performance_formatter_band_booking_performance_confirmation_icon($element) {
  // This code is specific to the Link field. It is based on theme_link_formatter_plain().
  if (!empty($element['element']['value'])) {
    return '<span class="icon icon-perf-' . $element['element']['value'] . '"></span>';
  } else {
    return '';
  }
}
