<?php

/**
 * @file
 * A module to manage Belive language installation.
 */

/**
 * Auto update po files foreach languages.
 */
function band_booking_language_auto_update_files() {
  // Import original translations foreach langcode.
  $band_booking_langcodes = band_booking_language_get_translation_langcodes();
  foreach ($band_booking_langcodes as $band_booking_langcode) {
    $folder = 'translations';
    $folder_path = drupal_get_path('module', 'band_booking_language') . '/' . $folder . '/' . $band_booking_langcode;
    $po_files_list = band_booking_language_list_po_files($folder_path);
    // @todo : test.
    _band_booking_language_import_translations_po_files($po_files_list, $folder, $band_booking_langcode);
  }
}

/**
 * Get the Belive available translations.
 *
 * @return array
 *   The array of Belive languages to look for.
 */
function band_booking_language_get_translation_langcodes() {
  $langcodes = array(
    0 => 'fr',
  );
  return $langcodes;
}

/**
 * This function creates locale_language, before import.
 *
 * @param array $langcodes
 *   Array of langcodes, folders with po files to import.
 */
function _band_booking_language_locale_add_language(array $langcodes) {
  foreach ($langcodes as $langcode) {
    // From here, $folder = langcode.
    locale_add_language($langcode, NULL, NULL, LANGUAGE_LTR, '', '', TRUE, TRUE);
  }
}

/**
 * Get a list of po files located in the folder $folder of the module.
 *
 * List only the .po located in subdirectories of $folder folder.
 *
 * @param string $folder_path
 *   The folder path to look for .po in.
 *
 * @return array
 *   Array of files ordered by language subfolders, empty array if no file
 *   found.
 */
function band_booking_language_list_po_files($folder_path) {
  $result = array();
  if (is_dir($folder_path)) {
    $files = new DirectoryIterator($folder_path);
    foreach ($files as $file) {
      if ($file->isDir()) {
        $subfiles = new DirectoryIterator($folder_path . '/' . $file->getFilename());
        foreach ($subfiles as $subfile) {
          if (substr($subfile->getFilename(), -3) == '.po') {
            $result[$file->getFilename()][$subfile->getFilename()] = $subfile->getFilename();
          }
        }
      }
    }
  }
  return $result;
}

/**
 * This function imports all po files which are in imported_folders folders.
 *
 * @param array $po_files_list
 *   Array of folders with po files to import.
 * @param string $folder
 *   The folder where to find sublanguages.
 * @param string $langcode
 *   Language code.
 */
function _band_booking_language_import_translations_po_files(array $po_files_list, $folder, $langcode) {
  // Add language to the drupal language list if it is not already set.
  // @todo : test.
  /*$languages = language_list();
  if (!isset($languages[$langcode])) {
    locale_add_language($langcode, NULL, NULL, LANGUAGE_LTR, '', '', TRUE, TRUE);
  }*/

  // Add each file for the current langcode.
  foreach ($po_files_list as $po_file) {
    foreach ($po_file as $file) {
      if (substr($file, -3) == '.po') {
        $f = new stdClass();
        $f->filename = $file;
        $f->uri = drupal_get_path('module', 'band_booking_language') . '/' . $folder . '/' . $langcode . '/' . $file;
        _locale_import_po($f, $langcode, LOCALE_IMPORT_OVERWRITE, 'default');
      }
    }
  }

}
