<?php

/**
 * @file
 * Code for the form to 
 */

/**
 * Build the form for accepting existing registrations.
 * 
 TODO
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param array $form_state
 *   The state of the form to build (not currently used).
 * @param stdClass $register
 *   The fully-loaded signup object with data about the signup to accept.
 * @param string $type
 *   The type of signup accept form to render, can be 'node', 'tab', or 'admin'.
 *
 * @return array
 *   The FAPI form array for the signup accept form.
 */
/*function belive_registration_node_registrations_view ($node) {
  drupal_set_title($node->title);
  //drupal_set_title('trucucucucu');
  return belive_registration_node_registrations_content();
}

function belive_registration_node_registrations_content() {
  return ('<p>grrzahetj</p>');
}*/