<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'band_booking_user.features.inc';

define('BB_ADMINISTRATOR_RID', 3);
define('BB_MANAGER_RID', 4);

function band_booking_user_menu() {
  return array(
    // Artist edit account redirection.
    'artist/edit-account' => array(
      'title' => 'Add performance',
      'page callback' => '_band_booking_user_goto_edit_page',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

function _band_booking_user_goto_edit_page() {
  global $user;
  $edit_path = 'user/' . $user->uid . '/edit';
  drupal_goto($edit_path);
}

/**
 * Alters form user pass.
 * @param $form
 * The form
 *
 * @param $form_state
 * @param $form_id
 */
function band_booking_user_form_user_pass_alter(&$form, &$form_state, $form_id) {
  $form['actions'][] = array(
    '#markup' => l(t('Log in'),'/user')
  );
}

/**
 * Implements hook_block_form_FORM_ID_alter().
 * Add a "request password" link
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function band_booking_user_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['actions'][] = array(
    '#markup' => l(t('Request new password'),'/user/password')
  );
}
